pod 'REComposeViewController', '~> 2.1.1'
pod 'SVProgressHUD', '~> 0.9'
pod 'TSMiniWebBrowser', '~> 1.0.1'
pod 'SDWebImage', '~> 3.2'
pod 'STTwitter', :git => 'https://github.com/govi/STTwitter.git'
pod 'STTweetLabel', :git => 'https://github.com/govi/STTweetLabel.git', :commit => '395c3ca5f8'